@startuml
'https://plantuml.com/class-diagram

class ToDoItem {
    -name : SimpleStringProperty
    -description : SimpleStringProperty
    -date : SimpleStringProperty
    -completed : SimpleStringProperty
    +getName() : String
    +getDescription() : String
    +getDate() : String
    +getCompleted() : String
    +setName()
    +setDescription()
    +setDate()
    +setCompleted()
}


@enduml